# Generated by Django 3.0.3 on 2020-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20200223_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='socialservice',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='socialservice',
            name='target',
        ),
        migrations.RemoveField(
            model_name='socialservice',
            name='website',
        ),
        migrations.AddField(
            model_name='socialservice',
            name='citizenship',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservice',
            name='household_income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservice',
            name='medisave_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservice',
            name='medishield_opt_out',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservice',
            name='support_type',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialservice',
            name='three_ADL',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
