# Generated by Django 3.0.3 on 2020-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20200304_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialservice',
            name='citizenship',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='household_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='medisave_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='medishield_opt_out',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='program',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='support_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='three_ADL',
            field=models.BooleanField(null=True),
        ),
    ]
