# Generated by Django 3.0.3 on 2020-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20200305_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialservice',
            name='household_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
