# Generated by Django 3.0.3 on 2020-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20200311_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialservice',
            name='medishield',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='pioneer_merdeka',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='three_ADL',
            field=models.IntegerField(null=True),
        ),
    ]
